server:
  port: 8080

spring:
  application:
    name: ddd-rbac-scaffold-lite
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  file:
    path: ./logs